### PR TITLE
some 2.8 fix

### PR DESCRIPTION
**Pull request by HuiProject**
I fix some issue,but I don't know how to make a base branch in your switch branch Button.

### CODE REVIEW

**Comment by patmo141** [comment]
Aaahhhh.  Ok I understand now.  So yes all of this work is excellent and needs to be done.  The OpenGL drawing is the next part that needs "updating" and it will be a total re-write but that's ok, we can strip some of that out for now.  I will figure out how to get a 2.80 branch started and see if we can do a pull request there.

**Comment by patmo141** [comment]
https://yangsu.github.io/pull-request-tutorial/

Ok, i have committed a few small fixes to master, and created a b_280 branch.  If you can alter your pull request to affect the b_280 branch then I am happy to merge it and I can start tinkering with the OpenGL drawing code from there.  Thank you for taking initiative on this!

**Comment by HuiProject** [comment]
OK！ I  already know,and I understand  update other programmer's branch's workflow.

**Comment by patmo141** [comment]
added you as a collaborator.  Got the b_280 branch working.  Thank you again for the push.  I would also love any help with documentation or tutorials.

**Pull request closed without merging**
